version: '3'

services:
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: react/app
    volumes:
      - .:/var/www/html
    ports:
      - "${APP_PORT}:3000"
    command: npm run start
    environment:
      - NODE_ENV=${NODE_ENV}